export const TOGGLE_TODO='TOGGLE_TODO';
export const ADD_TODO='ADD_TODO';
export const SET_VISIBILITY_FILTER='SET_VISIBILITY_FILTER';
export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_ERROR='FETCH_TODOS_ERROR';
